theme: jekyll-theme-cayman
title: "BelofteJS"
description: "A lightweight Promises/A+ compliant implementation of ECMAScript Promise API"
show_downloads: "true"
google_analytics: "UA-114357378-1"
theme_color: "#061166"
github:
  zip_url: "https://github.com/rousan/belofte.js/zipball/master"
  tar_url: "https://github.com/rousan/belofte.js/tarball/master"
